MissingMarks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("student.urls")),
    path('staff/', include("staff.urls")),
]

staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='staff_login'),
    path('marks/', views.staff_view, name='welcome'),
    path('staff/<int:pk>', views.resit_update, name='resit_edit'),
    path('sorted/', views.sort_view, name='sorted'),
    path('partially/', views.partially, name='partially'),
    path('add/user/', views.registrar, name='registrar'),
    path('registrar/home/', views.registrar_home, name='registrar_home'),
    path('logout/', views.staff_logout_view, name='staff_logout'),
    path('lecturer/', views.lecturer_view, name='lecturer'),
    path('password/', views.staff_change_password, name='staff_password'),
    path('cod/', views.cod_view, name='cod'),
    path('dean/', views.dean_view, name='dean'),
    path('some/', views.some_view, name='some_view'),
    path('base/', views.base_view, name='base_view'),
    path('cod/pdf', views.GeneratePdf.as_view(), name='dpdf'),
    path('cod/pdf/1', views.PDF2018.as_view(), name='dpdf1'),
    path('cod/pdf/2', views.PDF2017.as_view(), name='dpdf2'),
    path('cod/pdf/3', views.PDF2016.as_view(), name='dpdf3'),
    path('cod/pdf/4', views.PDF2015.as_view(), name='dpdf4'),
    path('dean/pdf/', views.GenerateFacultyPdf.as_view(), name='fpdf'),
    path('dean/pdf/1', views.FacultyPdf1.as_view(), name='fpdf1'),
    path('dean/pdf/2', views.FacultyPdf2.as_view(), name='fpdf2'),
    path('dean/pdf/3', views.FacultyPdf3.as_view(), name='fpdf3'),
    path('dean/pdf/4', views.FacultyPdf4.as_view(), name='fpdf4')
]

student/urls.py
from django.urls import path
from student import views
urlpatterns = [
    path('', views.login_page, name='login'),
    path('register/', views.register, name='register'),
    path('index/', views.index, name='index'),
    path('Change Password/', views.change_password, name='change_password'),
    path('logout/', views.logout_view, name='logout'),
    path('current/', views.current, name='current'),
    path('pending/', views.pending, name='pending'),
    path('previous/', views.previous, name='previous'),
    path('ajax/load-departments/', views.load_departments, name='ajax_load_departments'),
    path('ajax/load-lecs/', views.load_lecs, name='ajax_load_lecs'),
    path('ajax/load-units/', views.load_units, name='ajax_load_units'),
    path('ajax/val_unit/', views.validate_missing_marks, name='validate_missing_marks'),
]

missmark/models.py
from django.db import models

# Create your models here.
from student.models import StudentProfile, Faculty, Department, Unit
from staff.models import StaffProfile


class AcademicYears(models.Model):
    academic_year = models.CharField(max_length=9, primary_key=True)

    def __str__(self):
        return self.academic_year


class StudentMissingMark(models.Model):
    student_no = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    academic_year = models.ForeignKey(AcademicYears, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    taught_by = models.ForeignKey(StaffProfile, on_delete=models.CASCADE)
    year_choices = ((1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'))
    year = models.PositiveSmallIntegerField(choices=year_choices)
    sem_choices = ((1, 'I'), (2, 'II'), (3, 'III'))
    semester = models.PositiveSmallIntegerField(choices=sem_choices)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    seen_status = models.BooleanField(default=False)
    mm_status = models.BooleanField(default=False)
    comment = models.TextField(blank=True)

    class Meta:
        unique_together = ('student_no', 'unit')

    @property
    def dep_name(self):
        return self.unit.department.name

    @property
    def faculty_name(self):
        return self.unit.department.faculty.name

    @property
    def unit_code(self):
        return self.unit.unit_code

    def __str__(self):
        template = '{0.student_no}  {0.unit}'
        return template.format(self)

student/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
)
from MissingMarks import settings


# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, email, fullname, password=None, is_student=False, is_active=True, is_staff=False,
                    is_admin=False):
        if not email:
            raise ValueError("User must have an email address")
        if not password:
            raise ValueError("User must have a password")
        if not fullname:
            raise ValueError("User Must Have a Name")
        user_obj = self.model(
            email=self.normalize_email(email),
            fullname=fullname
        )
        user_obj.set_password(password)  # change password
        user_obj.student = is_student
        user_obj.staff = is_staff
        user_obj.active = is_active
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj

    def create_studentuser(self, email, fullname, password=None):
        user = self.create_user(email, fullname, password=password, is_student=True)
        return user

    def create_staffuser(self, email, fullname, password=None):
        user = self.create_user(email, fullname, password=password, is_staff=True)
        return user

    def create_superuser(self, email, fullname, password=None):
        user = self.create_user(email, fullname, password=password, is_staff=True, is_admin=True)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=30, unique=True, primary_key=True)
    fullname = models.CharField(max_length=255, blank=False, null=False)
    active = models.BooleanField(default=True)  # can login
    student = models.BooleanField(default=False)  # Student User
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'  # Username

    REQUIRED_FIELDS = ['fullname']

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    @staticmethod
    def has_perm(perm, obj=None):
        return True

    @staticmethod
    def has_module_perms(app_label):
        return True

    @property
    def is_student(self):
        return self.student

    @property
    def is_active(self):
        return self.active

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_staff(self):
        return self.staff


class StudentProfile(User):
    student_no = models.CharField(max_length=15, primary_key=True)
    phone_no = models.CharField(max_length=10, unique=True)
    faculty = models.ForeignKey('Faculty', on_delete=models.CASCADE, default=1)
    department = models.ForeignKey('Department', on_delete=models.CASCADE, default=1)
    gender_choices = ((2, 'MALE'), (3, 'FEMALE'))
    gender = models.PositiveSmallIntegerField(choices=gender_choices)

    def __str__(self):
        return self.student_no


class Faculty(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Faculty'
        verbose_name_plural = 'Faculties'

    def __str__(self):
        return self.name


class Department(models.Model):
    faculty = models.ForeignKey('Faculty', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Unit(models.Model):
    department = models.ForeignKey('Department', on_delete=models.CASCADE)
    year_choices = ((1, 1), (2, 2), (3, 3), (4, 4))
    year_offered = models.PositiveSmallIntegerField(choices=year_choices, default=1)
    unit_choices = ((1, 'CORE'), (2, 'SERVICE'))
    unit_type = models.PositiveSmallIntegerField(choices=unit_choices)
    unit_code = models.CharField(max_length=20, primary_key=True)
    unit_description = models.CharField(max_length=50)

    def __str__(self):
        return self.unit_code

student/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, redirect

from staff.models import StaffProfile
from student.models import Unit, StudentProfile, Department
from student.forms import LoginForm, StudentProfileForm
from missmark.models import StudentMissingMark
from missmark.forms import RegisterResitForm


# Create your views here.
def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            request.session['email'] = email
            cd = form.cleaned_data
            user = authenticate(email=cd['email'],
                                password=cd['password'])
            if user is not None:
                login(request, user)
                if request.user.student:
                    return redirect('index')
                else:
                    messages.error(request, 'Sorry you are not a student')
                    return render(request, 'accounts/login.html', {'form': form})
            else:
                messages.error(request, 'Sorry you are not a student')
                form = LoginForm()
                context = {'form': form}
                return render(request, 'accounts/login.html', context)
        else:
            messages.error(request, 'Sorry you are not a student')
            form = LoginForm()
            context = {'form': form}
            return render(request, 'accounts/login.html', context)

    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def register(request):
    if request.method == 'POST':
        form = StudentProfileForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(email=email, password=password)
            login(request, user)
            return redirect('index')
    else:
        form = StudentProfileForm()
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def index(request):
    if request.session.session_key is None:
        return redirect("login")
    else:
        if request.method == 'POST':
            form = RegisterResitForm(request.POST)
            if form.is_valid():
                resit = form.save(commit=False)
                re = StudentProfile.objects.get(
                    student_no=request.POST.get('student_no', request.user.studentprofile.student_no))
                print(re)
                resit.student_no = re
                resit.seen_status = request.POST['seen_status']
                resit.mm_status = request.POST['mm_status']
                resit.save()
                return redirect('current')
        else:
            form = RegisterResitForm(request.POST)
            cont = {'form': form}
            return render(request, 'app/index.html', cont)


def change_password(request):
    if request.session.session_key is None:
        return redirect("login")
    else:
        if request.method == 'POST':
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, 'Your password was successfully updated!')
                return redirect('index')
            else:
                messages.error(request, 'Please correct the error below.')
        else:
            form = PasswordChangeForm(request.user)
        return render(request, 'accounts/change_password.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')


def current(request):
    if request.session.session_key is None:
        return redirect("login")
    else:
        resit_list = StudentMissingMark.objects.filter(mm_status=False, seen_status=False,
                                                       student_no=request.user.studentprofile.student_no)
        print(request.user.studentprofile.student_no)
        context = {'resit_list': resit_list}
        return render(request, 'app/current.html', context)


def pending(request):
    if request.session.session_key is None:
        return redirect("login")
    else:
        resit_list = StudentMissingMark.objects.filter(mm_status=False, seen_status=True,
                                                       student_no=request.user.studentprofile.student_no)
        context = {'resit_list': resit_list}
        return render(request, 'app/pending.html', context)


def previous(request):
    if request.session.session_key is None:
        return redirect("login")
    else:
        resit_list = StudentMissingMark.objects.filter(mm_status=True,
                                                       student_no=request.user.studentprofile.student_no)
        context = {'resit_list': resit_list}
        return render(request, 'app/Previous.html', context)


def load_departments(request):
    faculty_id = request.GET.get('faculty')
    departments = Department.objects.filter(faculty_id=faculty_id).order_by('id')
    return render(request, 'app/departments_dropdown_list_options.html', {'departments': departments})


def load_lecs(request):
    department_id = request.GET.get('department')
    lecs = StaffProfile.objects.filter(department_id=department_id).order_by('staff_no')
    return render(request, 'app/taught_by_dropdown_list_options.html', {'lecs': lecs})


def load_units(request):
    department_id = request.GET.get('department')
    user_id = int(request.user.studentprofile.department_id)
    dep = int(request.GET.get('department'))
    print(user_id, dep)
    if user_id == dep:
        print(1)
        units = Unit.objects.filter(department_id=department_id, unit_type=1).order_by('year_offered')
        return render(request, 'app/units_dropdown_list_options.html', {'units': units})
    elif user_id != dep:
        print(2)
        units = Unit.objects.filter(department_id=department_id, unit_type=2).order_by('year_offered')
        return render(request, 'app/units_dropdown_list_options.html', {'units': units})


def validate_missing_marks(request):
    unit = request.GET.get('unit', None)
    data = {
        'is_taken': StudentMissingMark.objects.filter(unit=unit,
                                                      student_no=request.user.studentprofile.student_no).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'You have already booked this unit'
    return JsonResponse(data)

student/templates/app/departments_dropdown_list_options.html
<option value="">---------</option>
{% for department in departments %}
<option value="{{ department.pk }}">{{ department.name }}</option>
{% endfor %}

student/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/custom/pages.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"
                    aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Uni-Plus System</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <!-- Trigger the modal with a button -->
                <li>
                    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">HELP
                    </button>
                </li>
                <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span> Home </a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
                        Welcome {{ user.fullname }} <b class="caret"> </b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'change_password' %}"><span class="glyphicon glyphicon-edit"
                                                                        aria-hidden="true"></span>&nbsp; Change
                            Password
                        </a></li>
                        <li><a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Register Missing Marks Instructions</h4>
            </div>
            <div class="modal-body">
                <p>In this page you are expected to do the following:</p>
                <p>1. Use the <b>Faculty Offered</b> field to select the faculty where the unit is offered.</p>
                <p>2. Use the <b>Department Offered</b> field to select the department where the unit is offered.</p>
                <p>3. Use the <b>Unit Code</b> field to select the unit to register for a missing mark.</p>
                <p>4. Use the <b>Taught By</b> field to select the lecturer who taught the unit.</p>
                <p>5. Use the <b>Academic Year</b> field to select the academic year when you did the unit.</p>
                <p>6. Use the <b>Year Of Study</b> field to select your year of study when you did the unit.</p>
                <p>7. Use the <b>Semester Done</b> field to select the semester you did the unit.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div class="container-fluid">
    <div class="col-md-3 ">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>QUICK LINKS</h2>
                <br>
                <br>
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="{% url 'index' %}">Register Missing Marks</a></li>
                    <li><a href="{% url 'current' %}">Current Missing Marks</a></li>
                    <li><a href="{% url 'pending' %}">Pending Missing Marks</a></li>
                    <li><a href="{% url 'previous' %}">Previous Missing Marks</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default">
            <h1> Welcome {{ user.fullname }}</h1>
            <h2> Register Missing Mark.</h2>
            <br>
            <div class="panel-body">
                <form method="post" action="{% url 'index' %}" class="form-horizontal" id="missingform"
                      data-departments-url="{% url 'ajax_load_departments' %}"
                      data-lecs-url="{% url 'ajax_load_lecs' %}" data-units-url="{% url 'ajax_load_units' %}"
                      data-miss-url="{% url 'validate_missing_marks' %}">
                    {% csrf_token %}
{#                    {% if form.has_error %}#}
{#                            <p> There are errors in the form</p>#}
{#                        {% endif %}#}
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Faculty Offered: </label>
                        <div class="col-sm-9">
                            {{ form.faculty }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Department Offered: </label>
                        <div class="col-sm-9">
                            {{ form.department }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Unit Code: </label>
                        <div class="col-sm-9">
                            {{ form.unit }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Taught By: </label>
                        <div class="col-sm-9">
                            {{ form.taught_by }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Academic Year: </label>
                        <div class="col-sm-9">
                            {{ form.academic_year }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Year Of Study: </label>
                        <div class="col-sm-9">
                            {{ form.year }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Semester Of Study: </label>
                        <div class="col-sm-9">
                            {{ form.semester }}
                        </div>
                    </div>
                    <input name="student_no" type="hidden" value="{{ request.user.studentprofile }}">
                    <input type="hidden" name="seen_status" value="{{ 0 }}">
                    <input type="hidden" name="mm_status" value="{{ 0 }}">
                    <button class="btn btn-primary" type="submit">Register Missing mark</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $("#id_faculty").change(function () {
        var url = $("#missingform").attr("data-departments-url");  // get the url of the `load_departments` view
        var facultyId = $(this).val();  // get the selected faculty ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/app/ajax/load-departments/)
            data: {
                'faculty': facultyId       // add the faculty id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_` view function
                $("#id_department").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>
<script>
    $("#id_department").change(function () {
        var url = $("#missingform").attr("data-lecs-url");  // get the url of the `load_lecs` view
        var departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/app/ajax/load-lecs/)
            data: {
                'department': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_lecs` view function
                $("#id_taught_by").html(data);  // replace the contents of the lecs input with the data that came from the server
            }
        });

    });
</script>
<script>
    $("#id_department").change(function () {
        var url = $("#missingform").attr("data-units-url");  // get the url of the `load_units` view
        var departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/app/ajax/load-units/)
            data: {
                'department': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_units` view function
                $("#id_unit").html(data);  // replace the contents of the unit input with the data that came from the server
            }
        });

    });
</script>
<script>
    $("#id_unit").change(function () {
        var url = $("#missingform").attr("data-miss-url");
        var unit = $(this).val();
        var form = $(this).closest("#missingform");

        $.ajax({
            url: url,
            data: form.serialize(),
            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    alert(data.error_message);
                }
            }
        });

    });
</script>
</body>
</html>

student/templates/app/taught_by_dropdown_list_options.html
<option value="">---------</option>
{% for lec in lecs %}
<option value="{{ lec.pk }}">{{ lec.fullname }}</option>
{% endfor %}

student/templates/app/units_dropdown_list_options.html
<option value="">---------</option>
{% for unit in units %}
<option value="{{ unit.pk }}">{{ unit.unit_code }}</option>
{% endfor %}